<?php
/**
 * Dynamic discount / coupon generation. (Pro feature)
 *
 * @package FlexiReviveCartPro
 */

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class FRC_Pro_Discount
 */
class FRC_Pro_Discount {

	/**
	 * Inject discount data into the email template variables.
	 *
	 * Hooked to: frc_email_discount
	 *
	 * @param array  $discount Current discount data.
	 * @param object $cart     Cart row.
	 * @param string $type     Reminder type.
	 * @param int    $stage    Reminder stage.
	 * @return array
	 */
	public function inject_discount( $discount, $cart, $type, $stage ) {
		if ( ! get_option( 'frc_enable_auto_discounts', '0' ) ) {
			return $discount;
		}

		// Only inject discounts for incentive-type reminders or stage 3+.
		if ( 'incentive' !== $type && $stage < 3 ) {
			return $discount;
		}

		$code = $this->create_coupon( $cart );
		if ( empty( $code ) ) {
			return $discount;
		}

		$discount_type   = get_option( 'frc_discount_type', 'percent' );
		$discount_amount = (float) get_option( 'frc_discount_percentage', 10 );
		$expiry_days     = (int) get_option( 'frc_coupon_expiry_days', 7 );
		$expiry_unit     = get_option( 'frc_coupon_expiry_unit', 'days' );
		$expiry_seconds  = FRC_Helpers::convert_to_seconds( $expiry_days, $expiry_unit );

		$amount_label = 'percent' === $discount_type
			? $discount_amount . '%'
			: FRC_Helpers::format_currency( $discount_amount );

		$discount['code']   = $code;
		$discount['amount'] = $amount_label;
		$discount['expiry'] = gmdate( 'Y-m-d', time() + $expiry_seconds );

		// Store the discount code in the cart record.
		global $wpdb;
		$wpdb->update( // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery
			$wpdb->prefix . 'frc_abandoned_carts',
			array( 'discount_code' => $code ),
			array( 'id' => (int) $cart->id ),
			array( '%s' ),
			array( '%d' )
		);

		return $discount;
	}

	/**
	 * Create a unique WooCommerce coupon for a cart recovery.
	 *
	 * @param object $cart Cart row.
	 * @return string Coupon code, or empty string on failure.
	 */
	public function create_coupon( $cart ) {
		$code = $this->generate_coupon_code( $cart );

		// Return existing coupon code unchanged.
		$existing = $this->get_coupon_id_by_code( $code );
		if ( $existing ) {
			return $code;
		}

		$discount_type   = get_option( 'frc_discount_type', 'percent' );
		$discount_amount = (float) get_option( 'frc_discount_percentage', 10 );
		$min_cart_value  = (float) get_option( 'frc_min_cart_value', 0 );
		$expiry_days     = (int) get_option( 'frc_coupon_expiry_days', 7 );
		$usage_limit     = (int) get_option( 'frc_coupon_usage_limit', 1 );
		$exclude_sale    = (bool) get_option( 'frc_exclude_sale_items', '0' );

		$exclude_product_ids_raw = get_option( 'frc_exclude_product_ids', '' );
		$exclude_product_ids     = array_filter( array_map( 'absint', explode( ',', $exclude_product_ids_raw ) ) );

		$exclude_category_ids_raw = get_option( 'frc_exclude_category_ids', '' );
		$exclude_category_ids     = array_filter( array_map( 'absint', explode( ',', $exclude_category_ids_raw ) ) );

		$expiry_unit    = get_option( 'frc_coupon_expiry_unit', 'days' );
		$expiry_seconds = FRC_Helpers::convert_to_seconds( $expiry_days, $expiry_unit );
		$expiry_date    = gmdate( 'Y-m-d', time() + $expiry_seconds );

		$coupon = new WC_Coupon();
		$coupon->set_code( $code );
		$coupon->set_discount_type( in_array( $discount_type, array( 'percent', 'fixed_cart' ), true ) ? $discount_type : 'percent' );
		$coupon->set_amount( $discount_amount );
		$coupon->set_individual_use( true );
		$coupon->set_usage_limit( max( 1, $usage_limit ) );
		$coupon->set_usage_limit_per_user( 1 );
		$coupon->set_date_expires( strtotime( $expiry_date ) );

		if ( $min_cart_value > 0 ) {
			$coupon->set_minimum_amount( $min_cart_value );
		}
		if ( $exclude_sale ) {
			$coupon->set_exclude_sale_items( true );
		}
		if ( ! empty( $exclude_product_ids ) ) {
			$coupon->set_excluded_product_ids( array_values( $exclude_product_ids ) );
		}
		if ( ! empty( $exclude_category_ids ) ) {
			$coupon->set_excluded_product_categories( array_values( $exclude_category_ids ) );
		}

		$coupon->set_description( sprintf(
			/* translators: %d: cart ID */
			__( 'Auto-generated by Flexi Revive Cart for cart #%d', 'flexi-revive-cart-pro' ),
			(int) $cart->id
		) );
		$coupon->save();

		return $code;
	}

	/**
	 * Auto-apply the discount coupon when a cart is restored via recovery link.
	 *
	 * Hooked to: frc_cart_restored
	 *
	 * @param object $cart Cart row.
	 */
	public function auto_apply_coupon( $cart ) {
		if ( empty( $cart->discount_code ) ) {
			return;
		}

		if ( ! WC()->cart ) {
			return;
		}

		$applied = WC()->cart->get_applied_coupons();
		if ( ! in_array( $cart->discount_code, $applied, true ) ) {
			WC()->cart->apply_coupon( $cart->discount_code );
		}
	}

	/**
	 * Generate a unique coupon code for a cart.
	 *
	 * @param object $cart Cart row.
	 * @return string
	 */
	private function generate_coupon_code( $cart ) {
		$prefix = strtoupper( get_option( 'frc_coupon_prefix', 'RECOVER' ) );
		$suffix = strtoupper( get_option( 'frc_coupon_suffix', '' ) );
		$random = strtoupper( substr( $cart->recovery_token, 0, 8 ) );

		$parts = array_filter( array( $prefix, $random, $suffix ) );
		return implode( '-', $parts );
	}

	/**
	 * Get an existing coupon post ID by code.
	 *
	 * @param string $code Coupon code.
	 * @return int|null Post ID or null.
	 */
	private function get_coupon_id_by_code( $code ) {
		global $wpdb;
		$id = $wpdb->get_var( // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
			$wpdb->prepare(
				"SELECT ID FROM {$wpdb->posts} WHERE post_type = 'shop_coupon' AND post_title = %s LIMIT 1",
				$code
			)
		);
		return $id ? (int) $id : null;
	}
}
