<?php
/**
 * Dynamic discount / coupon generation. (Pro feature)
 *
 * @package FlexiReviveCart
 */

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class FRC_Discount_Manager
 */
class FRC_Discount_Manager {

	/**
	 * Create a unique WooCommerce coupon for a cart recovery.
	 *
	 * @param object $cart         Cart row.
	 * @param int    $discount_pct Discount percentage.
	 * @return string Coupon code.
	 */
	public function create_coupon( $cart, $discount_pct = 10 ) {
		if ( ! FRC_PRO_ACTIVE ) {
			return '';
		}

		$code = 'frc_' . strtolower( substr( $cart->recovery_token, 0, 8 ) );

		// Check if coupon already exists.
		$existing = $this->get_coupon_id_by_code( $code );
		if ( $existing ) {
			return $code;
		}

		$expiry_hours = (int) get_option( 'frc_coupon_expiry_hours', 72 );
		$expiry_date  = gmdate( 'Y-m-d', strtotime( '+' . $expiry_hours . ' hours' ) );

		$coupon = new WC_Coupon();
		$coupon->set_code( $code );
		$coupon->set_discount_type( 'percent' );
		$coupon->set_amount( (float) $discount_pct );
		$coupon->set_individual_use( true );
		$coupon->set_usage_limit( 1 );
		$coupon->set_date_expires( strtotime( $expiry_date ) );
		$coupon->set_description( sprintf(
			/* translators: %d: cart ID */
			__( 'Auto-generated by Flexi Revive Cart for cart #%d', 'flexi-revive-cart' ),
			(int) $cart->id
		) );
		$coupon->save();

		return $code;
	}

	/**
	 * Get an existing coupon post ID by code.
	 *
	 * @param string $code Coupon code.
	 * @return int|null Post ID or null.
	 */
	private function get_coupon_id_by_code( $code ) {
		global $wpdb;
		$id = $wpdb->get_var( // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
			$wpdb->prepare(
				"SELECT ID FROM {$wpdb->posts} WHERE post_type = 'shop_coupon' AND post_title = %s LIMIT 1",
				$code
			)
		);
		return $id ? (int) $id : null;
	}
}
