<?php
/**
 * Dynamic discount / coupon generation. (Pro feature)
 *
 * @package FlexiReviveCart
 */

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class FRC_Discount_Manager
 */
class FRC_Discount_Manager {

	/**
	 * Create a unique WooCommerce coupon for a cart recovery.
	 *
	 * Reads all coupon-rule settings from WordPress options and applies them
	 * to the generated WooCommerce coupon.
	 *
	 * @param object $cart         Cart row.
	 * @param int    $discount_pct Discount amount (percentage or fixed, depending on type).
	 * @return string Coupon code, or empty string when Pro is not active.
	 */
	public function create_coupon( $cart, $discount_pct = 10 ) {
		if ( ! FRC_PRO_ACTIVE ) {
			return '';
		}

		$code = $this->generate_coupon_code( $cart );

		// Return existing coupon code unchanged.
		$existing = $this->get_coupon_id_by_code( $code );
		if ( $existing ) {
			return $code;
		}

		// ── Discount rules ────────────────────────────────────────────────
		$discount_type   = get_option( 'frc_discount_type', 'percent' );
		$discount_amount = (float) get_option( 'frc_discount_percentage', $discount_pct );
		$min_cart_value  = (float) get_option( 'frc_min_cart_value', 0 );
		$expiry_days     = (int) get_option( 'frc_coupon_expiry_days', 7 );
		$usage_limit     = (int) get_option( 'frc_coupon_usage_limit', 1 );
		$exclude_sale    = (bool) get_option( 'frc_exclude_sale_items', '0' );

		// Excluded product IDs – stored as a comma-separated string.
		$exclude_product_ids_raw = get_option( 'frc_exclude_product_ids', '' );
		$exclude_product_ids     = array_filter( array_map( 'absint', explode( ',', $exclude_product_ids_raw ) ) );

		// Excluded category IDs – stored as a comma-separated string.
		$exclude_category_ids_raw = get_option( 'frc_exclude_category_ids', '' );
		$exclude_category_ids     = array_filter( array_map( 'absint', explode( ',', $exclude_category_ids_raw ) ) );

		// Expiry date computed dynamically from value + unit.
		$expiry_unit    = get_option( 'frc_coupon_expiry_unit', 'days' );
		$expiry_seconds = FRC_Helpers::convert_to_seconds( $expiry_days, $expiry_unit );
		$expiry_date    = gmdate( 'Y-m-d', time() + $expiry_seconds );

		// ── Build coupon ──────────────────────────────────────────────────
		$coupon = new WC_Coupon();
		$coupon->set_code( $code );
		$coupon->set_discount_type( in_array( $discount_type, array( 'percent', 'fixed_cart' ), true ) ? $discount_type : 'percent' );
		$coupon->set_amount( $discount_amount );
		$coupon->set_individual_use( true );
		// Ensure usage limit is at least 1; absint() can yield 0 for empty/invalid input.
		$coupon->set_usage_limit( max( 1, $usage_limit ) );
		$coupon->set_usage_limit_per_user( 1 );
		$coupon->set_date_expires( strtotime( $expiry_date ) );

		if ( $min_cart_value > 0 ) {
			$coupon->set_minimum_amount( $min_cart_value );
		}

		if ( $exclude_sale ) {
			$coupon->set_exclude_sale_items( true );
		}

		if ( ! empty( $exclude_product_ids ) ) {
			$coupon->set_excluded_product_ids( array_values( $exclude_product_ids ) );
		}

		if ( ! empty( $exclude_category_ids ) ) {
			$coupon->set_excluded_product_categories( array_values( $exclude_category_ids ) );
		}

		$coupon->set_description( sprintf(
			/* translators: %d: cart ID */
			__( 'Auto-generated by Flexi Revive Cart for cart #%d', 'flexi-revive-cart' ),
			(int) $cart->id
		) );
		$coupon->save();

		return $code;
	}

	/**
	 * Generate a unique coupon code for a cart using the configured prefix/suffix.
	 *
	 * Format: {PREFIX}-{RANDOM8}{-SUFFIX}
	 * Example: RECOVER-A1B2C3D4 or SUMMER2024-A1B2C3D4-VIP
	 *
	 * @param object $cart Cart row (used for a deterministic random segment).
	 * @return string Coupon code.
	 */
	public function generate_coupon_code( $cart ) {
		$prefix = strtoupper( get_option( 'frc_coupon_prefix', 'RECOVER' ) );
		$suffix = strtoupper( get_option( 'frc_coupon_suffix', '' ) );

		// Use first 8 chars of the cart's recovery token as the random segment so
		// the same coupon is always regenerated for the same cart.
		$random = strtoupper( substr( $cart->recovery_token, 0, 8 ) );

		$parts = array_filter( array( $prefix, $random, $suffix ) );
		return implode( '-', $parts );
	}

	/**
	 * Get an existing coupon post ID by code.
	 *
	 * @param string $code Coupon code.
	 * @return int|null Post ID or null.
	 */
	private function get_coupon_id_by_code( $code ) {
		global $wpdb;
		$id = $wpdb->get_var( // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
			$wpdb->prepare(
				"SELECT ID FROM {$wpdb->posts} WHERE post_type = 'shop_coupon' AND post_title = %s LIMIT 1",
				$code
			)
		);
		return $id ? (int) $id : null;
	}
}
